name: flutter_chips_selector
description: Flutter library for building input fields that covert text input into InputChips.
version: 0.0.10
homepage: https://github.com/skalio/flutter-chips-selector

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

